url: 'https://our-earth.github.io'
baseurl: '/demo'

title: 'Demo Articles'
description: 'AI-powered content & growth strategies that get results.'

paginate: 100
language: 'en-uk'
words_per_minute: 200

plugins_dir: ['_plugins']
plugins: ['jekyll-paginate', 'jekyll-feed']
