url: 'https://our-earth.github.io'
baseurl: '/demo'

title: 'Demo Drafts'
description: 'Client preview drafts'

paginate: 100
language: 'en-uk'
words_per_minute: 200

plugins_dir: ['_plugins']
plugins: ['jekyll-paginate', 'jekyll-feed']
