# ✨ Build & deploy Jekyll to GitHub Pages (with Actions) ✨
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ['master']   # ↖ change if your default branch is "main"
  workflow_dispatch:       # manual “Run workflow” button

permissions:
  contents: read           # required by checkout
  pages: write             # required to deploy
  id-token: write          # required by deploy-pages

concurrency:
  group: 'pages'
  cancel-in-progress: true # skip older queued runs; keep the newest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby & install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true   # installs & caches gems from Gemfile.lock

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl '${{ steps.pages.outputs.base_path }}'
        env:
          JEKYLL_ENV: production

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site            # default output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
